# This is a basic workflow to create a GitHub pull request when a git branch is pushed to the origin.
# Head branch is specified below: [on: -> pull_request: -> branches: -> main (switch this)].
# Base branch is specified below: [env: -> BASE_BRANCH: main (switch this)].
# Workflow utilizes Personal Access Token to create a pull request. 
# Create GitHub secret under repository called "PAT" containing personal access token with admin access to the repository.
# The user the PAT is associated with will always be the owner of the pull request. Lines 30-35 tags the user who triggered this job.

name: Automatically Create Pull Request

on:
  push:
    branches:
    - feature/*

env:
  BASE_BRANCH: develop

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:    
      - name: Create Pull Request from Feature Branch
        run: |
          curl -X POST "https://api.github.com/repos/${{ github.repository }}/pulls" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.ACUPACK_CREDS }}" \
            -d '{"head":"${{ github.ref_name }}","base":"${{ env.BASE_BRANCH }}","title":"${{ github.ref_name }}"}' \
            -o output.txt

          PULL_REQUEST_NUMBER=$(cat output.txt | jq -r '.number')

          curl -X POST "https://api.github.com/repos/${{ github.repository }}/issues/${PULL_REQUEST_NUMBER}/comments" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.ACUPACK_CREDS }}" \
            -d '{"body":"@${{ github.actor }}"}'